/* tslint:disable */
 


/**
 * AUTO-GENERATED FILE - DO NOT EDIT!
 *
 * This file was automatically generated by pg-to-ts v.4.1.1
 * $ pg-to-ts generate -c postgresql://username:password@supabase.digitlab.app:5432/postgres -t documents -t n8n_chat_histories -t order -t projects -t summary_prices -t table1 -t tasks -t tweets -t uk_postcode_to_iso -t uk_price_paid -s public
 *
 */


export type Json = unknown;
export type current_status = 'completed' | 'in-progress';

// Table projects
export interface Projects {
  id: number;
  created_at: Date;
  name: string;
  slug: string;
  description: string;
  status: current_status;
  collaborators: string[];
}
export interface ProjectsInput {
  id: number;
  created_at?: Date;
  name: string;
  slug: string;
  description: string;
  status?: current_status;
  collaborators?: string[];
}
const projects = {
  tableName: 'projects',
  columns: ['id', 'created_at', 'name', 'slug', 'description', 'status', 'collaborators'],
  requiredForInsert: ['id', 'name', 'slug', 'description'],
  primaryKey: 'id',
  foreignKeys: {},
  $type: null as unknown as Projects,
  $input: null as unknown as ProjectsInput
} as const;

// Table tasks
export interface Tasks {
  id: number;
  created_at: Date;
  name: string;
  status: current_status;
  description: string;
  due_date: Date | null;
  profile_id: string;
  project_id: number | null;
  collaborators: string[];
}
export interface TasksInput {
  id: number;
  created_at?: Date;
  name: string;
  status?: current_status;
  description: string;
  due_date?: Date | null;
  profile_id: string;
  project_id?: number | null;
  collaborators?: string[];
}
const tasks = {
  tableName: 'tasks',
  columns: ['id', 'created_at', 'name', 'status', 'description', 'due_date', 'profile_id', 'project_id', 'collaborators'],
  requiredForInsert: ['id', 'name', 'description', 'profile_id'],
  primaryKey: 'id',
  foreignKeys: { project_id: { table: 'projects', column: 'id', $type: null as unknown as Projects }, },
  $type: null as unknown as Tasks,
  $input: null as unknown as TasksInput
} as const;

// Table profiles
export interface Profiles {
  id: string;
  created_at: Date;
  username: string;
  full_name: string;
  bio: string | null;
  mode: string;
  avatar_url: string | null;
}
export interface ProfilesInput {
  id: string;
  created_at?: Date;
  username: string;
  full_name: string;
  bio?: string | null;
  mode?: string;
  avatar_url?: string | null;
}
const profiles = {
  tableName: 'profiles',
  columns: ['id', 'created_at', 'username', 'full_name', 'bio', 'mode', 'avatar_url'],
  requiredForInsert: ['id', 'username', 'full_name'],
  primaryKey: 'id',
  foreignKeys: { id: { table: 'users', column: 'id', $type: null as unknown /* users */ }, },
  $type: null as unknown as Profiles,
  $input: null as unknown as ProfilesInput
} as const;

export interface Database {
  projects: {
  select: Projects;
  input: ProjectsInput;
  };
  tasks: {
  select: Tasks;
  input: TasksInput;
  };
  profiles: {
    select: Profiles;
    input: ProfilesInput;
    };
}

export const tables = {
  projects,
  tasks,
  profiles
}
